# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Flutter CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          #flutter-version: 'stable'
          channel: stable
          flutter-version: 3.29.2

      # Instalăm dependențe și analizăm codul
      - name: Install dependencies
        run: flutter pub get

      - name: Analyze
        run: flutter analyze

      # Rulează unit & widget tests
      - name: Run tests
        run: flutter test --coverage

      #- name: Run integration tests
        #run: flutter test integration_test
        
        #run: flutter drive --driver=integration_test/driver.dart --target=integration_test/example_test.dart

      - name: Add google-services.json
        run: |
          mkdir -p android/app
          mkdir -p android/app/src
          mkdir -p android/app/src/release

          cat << 'EOF' > android/app/google-services.json
          ${{ secrets.GOOGLE_SERVICES_JSON }}
          EOF
          
          cp android/app/google-services.json android/app/src/google-services.json
          cp android/app/google-services.json android/app/src/release/google-services.json

      # build release 
      - name: Build Android APK
        run: flutter build apk --release

      # build & distribuie APK
      - name: Distribute to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
            appId: ${{ secrets.FIREBASE_APP_ID_ANDROID }}
            token: ${{ secrets.FIREBASE_TOKEN }}
            file: build/app/outputs/flutter-apk/app-release.apk
            groups: testers
